--A--
SELECT D.DAYNAME AS WEEKDAY, SUM(S.QTY * S.SALEPRICE) AS TOTAL_SALES
FROM DWDATE D
JOIN DWSALE S
ON D.DATEKEY = S.SALE_DWDATEID
GROUP BY D.DAYNAME
ORDER BY TOTAL_SALES DESC;
--B--
SELECT C.CUSTCATNAME, SUM(S.QTY) AS TOTAL_SALES
FROM DWCUST C
JOIN DWSALE S
ON C.DWCUSTID = S.DWCUSTID
GROUP BY C.CUSTCATNAME
ORDER BY TOTAL_SALES ASC;

--C--
SELECT P.PRODMANUNAME, SUM(S.QTY * S.SALEPRICE) AS TOTAL_QTY_SOLD
FROM DWPROD P
JOIN DWSALE S
ON P.DWPRODID = S.DWPRODID
GROUP BY P.PRODMANUNAME
ORDER BY TOTAL_QTY_SOLD;

--D--
SELECT C.DWCUSTID, C.FIRSTNAME, C.SURNAME, SUM(S.QTY * S.SALEPRICE) AS TOTAL_SALES
FROM  DWCUST C
JOIN DWSALE S
ON C.DWCUSTID = S.DWCUSTID
GROUP BY C.DWCUSTID, C.FIRSTNAME, C.SURNAME
ORDER BY TOTAL_SALES DESC
FETCH FIRST 10 ROWS ONLY;

--E--
SELECT P.DWPRODID, P.PRODNAME, SUM(S.QTY) AS TOTAL_SALES
FROM  DWPROD P
JOIN DWSALE S
ON P.DWPRODID = S.DWSALEID
GROUP BY P.DWPRODID, P.PRODNAME
ORDER BY TOTAL_SALES ASC
FETCH FIRST 10 ROWS ONLY;

--F--
SELECT C.STATE, C.CITY, SUM(S.QTY * S.SALEPRICE) AS TOTAL_SALES
FROM DWCUST C
JOIN DWSALE S
ON C.DWCUSTID = S.DWCUSTID
GROUP BY C.STATE, C.CITY
ORDER BY TOTAL_SALES ASC;